export enum MessageEnum {
	NOT_FOUND_WITH_ID = "message.NOT_FOUND_WITH_ID",
	NOT_FOUND = "message.NOT_FOUND",
	USER_NOT_OWNER = "message.USER_NOT_OWNER",
	UNAUTHORIZED = "message.UNAUTHORIZED",
	FIELD_REQUIRED = "message.FIELD_REQUIRED",
	MODIFY_DEFAULT = "message.MODIFY_DEFAULT",
	MINIMUM_FIELD = "message.MINIMUM_FIELD",
	INVALID_PAYLOAD = "message.INVALID_PAYLOAD",
	RETRIEVAL_FAILURE = "message.RETRIEVAL_FAILURE",
	INTERNAL_SERVER_ERROR = "message.INTERNAL_SERVER_ERROR"
}
