enum webhookEventType {
	CUSTOMER_BILLING_ADDERSS_UPDATED,
	CUSTOMER_CREATED,
	CUSTOMER_UPDATED,
	INVOICE_GENERATED,
	INVOICE_UPDATED,
	PAYMENT_FAILED,
	PAYMENT_REFUNDED,
	PAYMENT_SUCCEEDED,
	SUBSCRIPTION_CREATED,
	SUBSCRIPTION_STATUS_UPDATED,
	SUBSCRIPTION_UPDATED
}

export { webhookEventType }
